Foodplaner/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_views
import menu.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(menu.urls)),
    path("register/", users_views.register, name="register"),
    path("account/", users_views.account, name="account"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login"
    ),
    path(
        "logout/", auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"
    )
]

menu/urls.py
from django.urls import path
from . import views

app_name = "menu"
urlpatterns = [
    path("", views.home, name="home"),
    path("menu_am", views.menu_am, name="menu_am"),
    path("menu_pm", views.menu_pm, name="menu_pm")
]

menu/models.py
""" models of app menu
Product:
- name -> varchar
- recipe -> text
Date:
- day -> varchar
Menu
- name -> varchar
- notifsms -> boolean
- pk one-to-many(date)
-pk one-to-many(product)

"""

from django.db import models
from users.models import User


class Dish(models.Model):
    dish_name = models.CharField(max_length=120, null=False, unique=True)
    recipe = models.TextField(null=False, unique=True)
    ingredients = models.TextField(null=True, unique=True)
    serving = models.CharField(max_length=120, null=True)
    objects = models.Manager()

    def __str__(self):
        return self.dish_name


class Date(models.Model):
    day = models.CharField(max_length=120, null=False, unique=True)
    time_days = models.CharField(max_length=120, null=False, unique=False)
    objects = models.Manager()

    def __str__(self):
        return self.day


class Menu(models.Model):
    menu_name = models.CharField(max_length=120, null=False, unique=True)
    user_menu = models.ForeignKey(User, on_delete=models.CASCADE)
    menu_date = models.ManyToManyField(Date)
    menu_dish = models.ManyToManyField(Dish)
    objects = models.Manager()

    def __str__(self):
        return self.menu_name

users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class UserManager(BaseUserManager):
    def create_user(self, email, username, phone_number, password=None):
        """Creates and saves a User with the given data
        Args:
            email (str): Given email.
            username (str): Given username.
            password (str, optional): Given password. Defaults to None.
            phone_number (str): Given phone number
        Raises:
            ValueError: In case no email address entered
        Returns:
            obj: User
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            phone_number=phone_number,
        )

        user.set_password(password)  # hashes the pwd
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, phone_number, password=None):
        """Creates and saves a superuser with the given data
        Args:
            email (str): Given email.
            username (str): Given username.
            password (str, optional): Given password. Defaults to None.
        Returns:
            obj: Superuser
        """
        user = self.create_user(
            email,
            password=password,
            username=username,
            phone_number=phone_number,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    """Create table with custom fields in database"""

    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    username = models.CharField(max_length=60, default="utilisateur")
    phone_number = models.CharField(max_length=10, unique=True, null=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"  # login_field
    REQUIRED_FIELDS = ["username", "phone_number"]  # pwd is automatically required

    def __str__(self):
        return self.email

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True
    @property
    def is_staff(self):
        """Is the user a member of staff?"""
        # Simplest possible answer: All admins are staff
        return self.is_admin

menu/forms.py
from django import forms
from .models import Dish


class MenuForm(forms.Form):

    dish = forms.ModelChoiceField(queryset=Dish.objects.all())

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserRegistrationForm(UserCreationForm):
    """Customize form that create User"""
    email = forms.EmailField(max_length=254, help_text="Obligatoire")
    username = forms.CharField(max_length=60, help_text="Obligatoire")

    class Meta:
        model = User
        fields = ["email", "username", "phone_number", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    """customize form for updating user information"""
    email = forms.EmailField(initial=None, max_length=254)
    username = forms.CharField(initial=None, max_length=254)
    phone_number = forms.CharField(initial=None, max_length=12)

    class Meta:
        model = User
        fields = ["email", "username", "phone_number"]

menu/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.forms import formset_factory
from .models import Dish
from .forms import MenuForm


def home(request):
    return render(request, 'menu/home.html')


def menu_am(request):
    DishFormSet = formset_factory(form=MenuForm, extra=7)
    formset = DishFormSet()
    if request.method == "POST":
        formset2 = DishFormSet(request.POST)
        if formset2.is_valid():
            for form in formset2:
                if form.is_valid():
                    return HttpResponse(form.cleaned_data)
    return render(request, 'menu/menu_am.html', {'formset': formset})


def menu_pm(request):
    menuform = MenuForm()
    context = {'menuform': menuform}
    return render(request, 'menu/menu_pm.html', context)

users/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate

# uses custom form instead of UserCreationForm
from .forms import UserRegistrationForm, UserUpdateForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect


def register(request):
    """Displays the registration page"""
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            # Login automatically
            email = form.cleaned_data.get("email")
            raw_password = form.cleaned_data.get("password1")
            messages.success(
                request, f"Compte créé pour l'adresse email : {email} !")
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect("menu/home.html")
    else:
        form = UserRegistrationForm()
    return render(
        request, "users/register.html", {"form": form}
    )  # form as a context to be used in template


@login_required  # only allows this page to logged_in users
def account(request):
    """Displays the account page when a user is logged in"""
    if request.method == "POST":
        update_user_form = UserUpdateForm(request.POST, instance=request.user)
        if update_user_form.is_valid():
            update_user_form.save()
            messages.success(request, f"Votre compte à été mis à jour !")
            return redirect('account')
    else:
        update_user_form = UserUpdateForm(instance=request.user)
        context = {
            "update_user_form": update_user_form
        }
        return render(request, "users/account.html", context)

menu/templates/menu/home.html
{% extends 'base.html' %}
{% block content %}{% load static %}
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">What are we eating this week ?</h1>
                        <h2 class="text-white font-weight-bold">
                        Don't think anymore create your menu for the week and get notify by sms</h2>
                        <hr class="divider"/>
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                    <a href="{% url 'login' %}" id='btn_redirect_login' class="btn btn-outline-primary">it's over here</button>
                    </a>
                    </div>
                </div>
            </div>
        </header>
{% endblock content %}

menu/templates/menu/menu_am.html
{% extends 'base.html' %}
{% block content %}{% load static %}
        <header class="masthead" style="height: 29vh">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">your menu for lunch's</h1>
                    </div>
                </div>
            </div>
        </header>
        <section>
        <div class="container-fluid define-size-2 z-index-block">
        <div class="row h-100">
            <div class="col-12 col-lg-10 offset-lg-1 h-100 overflow-scroll" id="divContent">
                <table class="table table-striped table-dark" id="table{{ user.id }}">
                    <thead>
                        <tr class="text-center">
                            <th scope="col">Sunday</th>
                            <th scope="col">Monday</th>
                            <th scope="col">Tuesday</th>
                            <th scope="col">Wednesday</th>
                            <th scope="col">Thursday</th>
                            <th scope="col">Friday</th>
                            <th scope="col">Saturday</th>
                            <th scope="col">#</th>
                        </tr>
                    </thead>
                    <tbody>
                    <form method='POST' enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ formset.management_form }}
                                {% for form in formset %}
                                    {{form.as_table}}
                                {% endfor %}
                                <div class="d-flex-inline">
                                    <button type="button" class="btn btn-warning text-white" id="btnNotif"><i class="fas fa-bell"></i></button>
                                    <button type="submit" class="btn btn-success" id="btnValidPlanning"><i class="fas fa-check"></i></button>
                                    <button type="button" class="btn btn-primary" id="btnEditPlanning"><i class="fas fa-pencil-alt"></i></button>
                                    <button type="button" class="btn btn-danger" id="btnRemovePlanning}"><i class="fas fa-trash-alt"></i></button>
                                </div>
                       </form>
                    </tbody>
                </table>
            </div>  <!-- end .col-12 -->
        </div> <!-- end .row -->
    </div> <!-- end .container-fluid -->
</section>
{% endblock content %}

menu/templates/menu/menu_pm.html
{% extends 'base.html' %}
{% block content %}{% load static %}
        <header class="masthead" style="height: 29vh">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Your menu for your dinner's</h1>
                    </div>
                </div>
            </div>
        </header>
        <section>
        <div class="container-fluid define-size-2 z-index-block">
        <div class="row h-100">
            <div class="col-12 col-lg-10 offset-lg-1 h-100" id="divContent">
                <p class="lead text-white mt-5 animated fadeIn" id="userPlanning">Planning pour {{user.usernane}}</p>
                <p class="d-none animated fadeIn" id="idUserDb"></p>
                <p class="d-none animated fadeIn" id="idUserPlanning"></p>
                <table class="table table-striped table-dark animated fadeIn" id="table{{ user.id }}">
                    <thead>
                        <tr class="text-center">
                            <th scope="col">Sunday</th>
                            <th scope="col">Monday</th>
                            <th scope="col">Tuesday</th>
                            <th scope="col">Wednesday</th>
                            <th scope="col">Thursday</th>
                            <th scope="col">Friday</th>
                            <th scope="col">Saturday</th>
                            <th scope="col">#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="text-center" id='trDish{{ user.id }}'>
                            <td id="plat-lu-pl-1">
                                {{ menuform }}
                            <td id="plat-ma-pl-1">
                                {{ menuform }}
                            </td>
                            <td id="plat-me-pl-1">
                                 {{ menuform }}
                            </td>
                            <td id="plat-je-pl-1">
                             {{ menuform }}
                            </td>
                            <td id="plat-ve-pl-1">
                            {{ menuform }}
                            </td>
                            <td id="plat-sa-pl-1">
                             {{ menuform }}
                            </td>
                            <td id="plat-di-pl-1">
                             {{ menuform }}
                            </td>

                            <td>
                                <div class="d-flex-inline">
                                    <button type="button" class="btn btn-warning text-white" id="btnNotif"><i class="fas fa-bell"></i></button>
                                    <button type="button" class="btn btn-success" id="btnValidPlanning" disabled><i class="fas fa-check"></i></button>
                                    <button type="button" class="btn btn-primary" id="btnEditPlanning"><i class="fas fa-pencil-alt"></i></button>
                                    <button type="button" class="btn btn-danger" id="btnRemovePlanning}"><i class="fas fa-trash-alt"></i></button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>  <!-- end .col-12 -->
        </div> <!-- end .row -->
    </div> <!-- end .container-fluid -->
    </section>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Fontawsome-->
        <script
        src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous">
      </script>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'dist/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
    <!-- Navigation-->
    {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <img src="{% static 'dist/assets/img/logo.png'%}" style="margin-right: 1em" width="60px" height="40px" class="d-inline-block align-top" alt="">
                <a class="navbar-brand" href="{% url 'menu:home' %}"> Foodplanner </a>
                <button class="navbar-toggler navbar-toggler-right"
                type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item">
                         {% if user.is_authenticated %}
                            <a href="{% url 'account' %}"id="mon_compte"
                            class="nav-link js-scroll-trigger" title="Mon compte">
                        <i class="fa-2x fas fa-user-alt"></i>
                        </a>
                        {% else %}
                      <a href="{% url 'login'%}"
                        class="nav-link js-scroll-trigger" title="Se connecter">
                        <i class="fa-2x fas fa-sign-in-alt"></i>
                      </a>
                      {% endif %}
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a href="{% url 'menu:menu_am' %}"
                        class="nav-link js-scroll-trigger" title="Midi">
                        <i class="fa-2x fas fa-sun"></i>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'menu:menu_pm' %}"
                        class="nav-link js-scroll-trigger" title="Soir">
                        <i class="fa-2x fas fa-moon"></i>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'logout' %}"
                        class="nav-link js-scroll-trigger" title="Se déconnecter">
                        <i class="fa-2x fas fa-sign-out-alt"></i
                      ></a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </nav>
    {% endblock nav%}

    {% block content %}
    {% endblock content %}

    {% block footer %}
    <footer class="bg-light py-3">
        <div class="container">
            <div class="row" style="justify-content: center">
                <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                    <a href="">Legal mentions</a>
                </div>
                <div class="col-lg-4 mr-auto text-center mb-5 mb-lg-0">
                    <a href="#contact">Contact</a>
              </div>
        </div>
      </div>
    </footer>
    {% endblock footer %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'dist/js/scripts.js' %}"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <!-- jQueryUI -->
        <script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
          integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
          integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
          integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

users/templates/users/account.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %} {% block content %} {% load static %}

<!-- Authentication -->
<header class="masthead" style="height:29vh">
  <div class="container h-100">
    <div
      class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">My account</h1>
        <hr class="divider my-4" />
      </div>
    </div>
  </div>
</header>
<section class="page-section bg-light" id="account">
  <div class="container">
       <div class="row h-100">
            <h3 style="margin-bottom:2rem">Your account information </h3>
            <p><strong>your email address :</strong> {{ user.email }}</p>
            <p><strong>your username :</strong> {{ user.username }}</p>
            <p><strong>your phone number:</strong> {{ user.phone_number }}</p>
    </div>
    <h3 style="margin-top:2rem">Update your profile</h3>
    <form method="POST">
                {% csrf_token%}
                <fieldset class="form-group" enctype="multipart/form-data">
                    {{ update_user_form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-primary" style ="margin-top: 1rem" type="submit">Update</button>
                </div>
            </form>
  </div>
</section>

{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %} {% block content %} {% load static %}

<!-- Authentication -->
<header class="masthead" style="height: 29vh">
  <div class="container h-100">
    <div
      class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Login</h1>
        <hr class="divider my-4" />
      </div>
    </div>
  </div>
</header>

<section class="page-section bg-light" id="login">
  <div class="container">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">{{ form|crispy }}</fieldset>

      <button type="submit" class="btn btn-primary" style ="margin-top: 1rem">Login</button>
    </form>
    <div class="mt-3">
      <a
        href="{% url 'register' %}"class="btn btn-secondary"
        role="button" aria-pressed="true">
        Register
        </a>
    </div>
  </div>
</section>
{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %} {% load static %}

<!-- Authentication -->
<header class="masthead" style="height: 29vh">
  <div class="container h-100">
    <div
      class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Logout</h1>
        <hr class="divider my-4" />
      </div>
    </div>
  </div>
</header>
<section class="page-section bg-light" id="account">
  <div class="container">
    <h1 class="text-center">  Goodbye see you soon ! {{ user.email }} ! </h1>
  </div>
</section>


{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}{% load static %}
    <!-- Registration -->
    <header class="masthead" style="height: 29vh">
        <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-8 align-self-end">
                    <h1 class="text-white font-weight-bold">Registration</h1>
                </div>
                <div class="col-lg-8 align-self-baseline">

                </div>
            </div>
        </div>
    </header>
    <section class="page-section bg-light" id="register">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <!-- protects form, needed to work -->
                <fieldset class="form-group">{{ form|crispy }}</fieldset>

                <button type="submit" name="btn-register" id="btn-register" class="btn btn-primary" style="margin-top:1rem">Registration</button>
            </form>
            <div class="mt-3">
                <a href="{% url 'login' %}"
                   class="btn btn-secondary"
                   role="button"
                   aria-pressed="true">
                    account already exist</a>
            </div>
        </div>
    </section>
{% endblock %}